### ISSUE TITLE
Board thickness specification

### ISSUE THREAD

**Issue by jonnew** [daharoni/Miniscope_CMOS_Imaging_Sensor_PCB#2]
Does the image sensor PCB have to be a particular thickness? I could not find this spec on the .docx file with assembly info.

**Comment by daharoni** [comment]
The recommended thickness is in the fabrication CMOSv3_2_PCB_Fab_Info.docx and is 0.031" (half the thickness of standard PCBs). There is no strict requirement on the thickness of this PCB but the thinner the PCB the lighter the entire system will be. I think 0.031" is a good balance between weight, rigidness, and ease of finding a fabrication house that can make it.

**Comment by jonnew** [comment]
Great! 0.8mm it is.
